### ISSUE TITLE
url checks

### ISSUE THREAD

**Issue by chenweiLabri** [mrs-sam/page#2]
it appears that email and pdf files are not filtered out

**Comment by chenweiLabri** [comment]
if ((hrefUri.protocol() != 'http') && (hrefUri.protocol() != 'https'))
        return false;

//http or https.  if it is a email, its protocol is 'mailto', so the email has bean excluded.

**Comment by chenweiLabri** [comment]
var pathTokens = hrefUri.path().split('.');
    if (pathTokens.length > 1 && pathTokens[pathTokens.length - 1].toLowerCase() != 'html' && pathTokens[pathTokens.length - 1].toLowerCase() != 'php')
        return false;



//not only html, some are # **_php_**, which should be included.

**Comment by chenweiLabri** [comment]
pathTokens has exclude '.pdf' and '.xml'

**Comment by xblanc33** [comment]
Wei, if you fix the bug, you should send a pull request ;)

**Comment by xblanc33** [comment]
good !
